{
 "title": "Google Campaigns",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Platform",
    "query": "SELECT DISTINCT platform FROM output.google_campaign_report"
   },
   {
    "name": "Type",
    "query": "SELECT DISTINCT campaign_type FROM output.google_campaign_report WHERE platform in($Platform) "
   },
   {
    "name": "BrandProduct",
    "query": "SELECT DISTINCT brandorproduct FROM output.google_campaign_report WHERE platform in($Platform) AND campaign_type in($Type)"
   },
   {
    "name": "Campaign",
    "query": "SELECT DISTINCT campaign FROM output.google_campaign_report WHERE platform in($Platform) AND campaign_type in($Type) AND brandorproduct in($BrandProduct)"
   },
   {
    "name": "ConversionCategory",
    "query": "SELECT DISTINCT conversion_action_category FROM output.google_conversion_campaign_report"
   },
   {
    "name": "ConversionAction",
    "query": "SELECT DISTINCT conversion_action_name FROM output.google_conversion_campaign_report WHERE conversion_action_category in($ConversionCategory)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Ads</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Media Spend",
   "type": "stat",
   "description": "Total cost in DKK",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(cost) AS \"cost\"\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)\n"
    }
   ]
  },
  {
   "title": "Conversion Value",
   "type": "stat",
   "description": "An action that's counted when someone interacts with your ad (for example, clicks a text ad or views a video ad) and then takes an action that you’ve defined as valuable to your business, such as an online purchase or a call to your business from a mobile phone.",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(conversions_value) AS \"conversions\"\nFROM google_conversion_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign) AND \n  conversion_action_category in($ConversionCategory) AND\n  conversion_action_name in($ConversionAction)"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "stat",
   "description": "The number of clicks",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(clicks) AS \"clicks\"\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 8 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Statistics - Campaign View</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Media Spend",
   "type": "graph",
   "description": "Cost in DKK",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(cost) AS \"cost\",\n  name\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)\nGROUP BY 1, name\nORDER BY date"
    }
   ]
  },
  {
   "title": "Conversion Value - Campaign Level",
   "type": "graph",
   "description": "Conversion value is a measure of the value of all the conversions given a self defined value metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(conversions_value) AS \"conversions_value\",\n  name\nFROM google_conversion_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign) AND \n  conversion_action_category in($ConversionCategory) AND\n  conversion_action_name in($ConversionAction)\nGROUP BY 1, name\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "CPA",
   "type": "graph",
   "description": "Cost per acquisition\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH conversions as (\n  SELECT\n    date, name, sum(conversions) as \"conversions\"\n  FROM google_conversion_campaign_report\n  WHERE \n    platform in($Platform) AND \n    campaign_type in($Type) AND \n    brandorproduct in($BrandProduct) AND\n    campaign in($Campaign) AND\n    conversion_action_category in($ConversionCategory) AND\n    conversion_action_name in($ConversionAction)\n  GROUP BY name, date),\ncost AS (\n  SELECT name, date, sum(cost) as \"cost\"\n  FROM google_campaign_report\n  WHERE \n    $__timeFilter(date) AND\n    platform in($Platform) AND \n    campaign_type in($Type) AND \n    brandorproduct in($BrandProduct) AND\n    campaign in($Campaign)\n    GROUP BY name, date)\nSELECT \n  $__timeGroupAlias(conversions.date,$__interval),\n  conversions / cost AS \"cpa\",\n  conversions.name\nFROM conversions LEFT JOIN cost \nON conversions.name = cost.name AND conversions.date = cost.date\nWHERE\n  $__timeFilter(conversions.date)\nGROUP BY 1, name"
    }
   ]
  },
  {
   "title": "ROAS",
   "type": "graph",
   "description": "Return of Ad Spend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH conversions as (\n  SELECT\n    date, name, sum(conversions_value) as \"conversions_value\"\n  FROM google_conversion_campaign_report\n  WHERE \n    platform in($Platform) AND \n    campaign_type in($Type) AND \n    brandorproduct in($BrandProduct) AND\n    campaign in($Campaign) AND\n    conversion_action_category in($ConversionCategory) AND\n    conversion_action_name in($ConversionAction)\n  GROUP BY name, date),\ncost AS (\n  SELECT name, date, sum(cost) as \"cost\"\n  FROM google_campaign_report\n  WHERE \n    $__timeFilter(date) AND\n    platform in($Platform) AND \n    campaign_type in($Type) AND \n    brandorproduct in($BrandProduct) AND\n    campaign in($Campaign)\n    GROUP BY name, date)\nSELECT \n  $__timeGroupAlias(conversions.date,$__interval),\n  conversions_value / cost AS \"roas\",\n  conversions.name\nFROM conversions LEFT JOIN cost \nON conversions.name = cost.name AND conversions.date = cost.date\nWHERE\n  $__timeFilter(conversions.date)\nGROUP BY 1, name"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "graph",
   "description": "The number of clicks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(clicks) AS \"clicks\",\n  name\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign) \nGROUP BY 1, name\nORDER BY date"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "graph",
   "description": "How often your ad is shown. An impression is counted each time your ad is shown on a search result page or other site on the Google Network.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(Impressions) AS \"Impressions\",\n  name\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)\nGROUP BY 1, name\nORDER BY date"
    }
   ]
  },
  {
   "title": "CTR",
   "type": "graph",
   "description": "A ratio showing how often people who see your ad end up clicking it. Clickthrough rate (CTR) can be used to gauge how well your keywords and ads are performing.\n",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(ctr) AS \"ctr\",\n  name\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)\nGROUP BY 1, name\nORDER BY date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 42 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Statistics - Conversion Value View</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Conversion Goals",
   "type": "graph",
   "description": "An action that's counted when someone interacts with your ad (for example, clicks a text ad or views a video ad) and then takes an action that you’ve defined as valuable to your business, such as an online purchase or a call to your business from a mobile phone.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  conversions as \"conversions\",\n  conversion_action_name\nFROM google_conversion_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign) AND \n  conversion_action_category in($ConversionCategory) AND \n  conversion_action_name in($ConversionAction)\nGROUP BY 1, conversion_action_name\nORDER BY date"
    }
   ]
  },
  {
   "title": "Conversion Value",
   "type": "graph",
   "description": "Conversion Value is a measure of the value of all the conversions given a self defined value metric",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  conversions_value as \"conversions_value\",\n  conversion_action_name\nFROM google_conversion_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign) AND \n  conversion_action_category in($ConversionCategory) AND \n  conversion_action_name in($ConversionAction)\nGROUP BY 1, conversion_action_name\nORDER BY date"
    }
   ]
  },
  {
   "title": "Clicks per device type",
   "type": "bargauge",
   "description": "The number of clicks",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(clicks) AS \"clicks\",\n  device\nFROM google_device_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  platform in($Platform) AND \n  campaign_type in($Type) AND \n  brandorproduct in($BrandProduct) AND\n  campaign in($Campaign)\nGROUP BY device\nORDER BY clicks DESC;"
    }
   ]
  },
  {
   "title": "Media spend on campaigns",
   "type": "bargauge",
   "description": "Cost in DKK",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(cost) AS \"cost\",\n  name\nFROM google_campaign_report\nWHERE\n  $__timeFilter(date)\nGROUP BY name\nORDER BY cost DESC;"
    }
   ]
  },
  {
   "title": "Conversion value on campaigns",
   "type": "bargauge",
   "description": "Conversion value of all types of conversions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(conversions_value) AS \"conversions_value\",\n  name\nFROM google_conversion_campaign_report\nWHERE\n  $__timeFilter(date)\nGROUP BY name\nORDER BY conversions_value DESC;"
    }
   ]
  }
 ]
}