{
 "title": "Google Campaign Manager",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Brand",
    "query": "SELECT DISTINCT brand FROM output.google_cm_campaign_report"
   },
   {
    "name": "Product",
    "query": "SELECT DISTINCT product FROM output.google_cm_campaign_report WHERE brand in($Brand) "
   },
   {
    "name": "Campaign",
    "query": "SELECT DISTINCT campaign_name FROM output.google_cm_campaign_report WHERE brand in($Brand)  AND product in($Product)"
   },
   {
    "name": "Creative",
    "query": "SELECT DISTINCT creative FROM output.google_cm_campaign_report"
   },
   {
    "name": "Activity",
    "query": "SELECT DISTINCT activity FROM output.google_cm_conversion_report"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Campaign Manager</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Media Spend",
   "type": "stat",
   "description": "Total cost i DKK",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(cost) AS \"cost\"\nFROM google_cm_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  brand in(Brand) AND \n  product in(Product) AND \n  campaign_name in($Campaign) AND \n  creative in($Creative)"
    }
   ]
  },
  {
   "title": "Conversion Value",
   "type": "stat",
   "description": "An action that's counted when someone interacts with your ad (for example, clicks a text ad or views a video ad) and then takes an action that you’ve defined as valuable to your business, such as an online purchase or a call to your business from a mobile phone.",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(conversions_value) AS \"conversions_value\"\nFROM google_cm_conversion_report\nWHERE\n  $__timeFilter(date) AND\n  brand in($Brand) AND \n  product in($Product) AND \n  campaign_name in($Campaign) AND \n  activity in ($Activity)"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "stat",
   "description": "The number of clicks",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(clicks) AS \"clicks\"\nFROM google_cm_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  brand in(Brand) AND \n  product in(Product) AND \n  campaign_name in($Campaign) AND \n  creative in($Creative)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 8 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Statistics - Campaign View</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Media Spend",
   "type": "graph",
   "description": "Cost in DKK",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(cost) AS \"cost\",\n  campaign_name\nFROM google_cm_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  brand in(Brand) AND \n  product in(Product) AND \n  campaign_name in($Campaign) AND \n  creative in($Creative)\nGROUP BY time, campaign_name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Conversion Value - Campaign Level",
   "type": "graph",
   "description": "Conversion value is a measure of the value of all the conversions given a self defined value metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date as \"time\",\n  sum(conversions_value) AS \"conversions_value\",\n  campaign_name\nFROM google_cm_conversion_report\nWHERE\n  $__timeFilter(date) AND\n  brand in($Brand) AND \n  product in($Product) AND \n  campaign_name in($Campaign) AND \n  activity in ($Activity)\nGROUP BY time, campaign_name\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPA",
   "type": "graph",
   "description": "Cost per acquisition\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH conversions as (\n  SELECT\n    date, campaign_name, sum(conversions) as \"conversions\"\n  FROM google_cm_conversion_report\n  WHERE \n    brand in($Brand) AND \n    product in($Product) AND \n    campaign_name in($Campaign) AND \n    activity in ($Activity)\n  GROUP BY campaign_name, date),\ncost AS (\n  SELECT campaign_name, date, sum(cost) as \"cost\"\n  FROM google_cm_campaign_report\n  WHERE \n    $__timeFilter(date) AND\n    brand in($Brand) AND \n    product in($Product) AND \n    campaign_name in($Campaign) AND \n    creative in($Creative)\n    GROUP BY campaign_name, date)\nSELECT \n  $__timeGroupAlias(conversions.date,$__interval),\n  conversions / cost AS \"cpa\",\n  conversions.campaign_name\nFROM conversions LEFT JOIN cost \nON conversions.campaign_name = cost.campaign_name AND conversions.date = cost.date\nWHERE\n  $__timeFilter(conversions.date)\nGROUP BY 1, campaign_name"
    }
   ]
  },
  {
   "title": "ROAS",
   "type": "graph",
   "description": "Return of Ad Spend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH conversions as (\n  SELECT\n    date, campaign_name, sum(conversions_value) as \"conversions_value\"\n  FROM google_cm_conversion_report\n  WHERE \n    brand in($Brand) AND \n    product in($Product) AND \n    campaign_name in($Campaign) AND \n    activity in ($Activity)\n  GROUP BY campaign_name, date),\ncost AS (\n  SELECT campaign_name, date, sum(cost) as \"cost\"\n  FROM google_cm_campaign_report\n  WHERE \n    $__timeFilter(date) AND\n    brand in($Brand) AND \n    product in($Product) AND \n    campaign_name in($Campaign) \n    GROUP BY campaign_name, date)\nSELECT \n  $__timeGroupAlias(conversions.date,$__interval),\n  conversions_value / cost AS \"cpa\",\n  conversions.campaign_name\nFROM conversions LEFT JOIN cost \nON conversions.campaign_name = cost.campaign_name AND conversions.date = cost.date\nWHERE\n  $__timeFilter(conversions.date)\nGROUP BY 1, campaign_name"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "graph",
   "description": "The number of clicks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(clicks) AS \"clicks\",\n  campaign_name\nFROM google_cm_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  brand in(Brand) AND \n  product in(Product) AND \n  campaign_name in($Campaign) AND \n  creative in($Creative)\nGROUP BY 1, campaign_name\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "graph",
   "description": "How often your ad is shown. An impression is counted each time your ad is shown on a search result page or other site on the Google Network.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(impressions) AS \"impressions\",\n  campaign_name\nFROM google_cm_campaign_report\nWHERE\n  $__timeFilter(date) AND\n  brand in(Brand) AND \n  product in(Product) AND \n  campaign_name in($Campaign) AND \n  creative in($Creative)\nGROUP BY 1, campaign_name\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 34 },
   "content": "\n<h1><p style=\"text-align: center;\">Google Statistics - Conversion Value View</p></h1>\n\n<hr class=\"rounded\">\n"
  },
  {
   "title": "Conversion Goals",
   "type": "graph",
   "description": "An action that's counted when someone interacts with your ad (for example, clicks a text ad or views a video ad) and then takes an action that you’ve defined as valuable to your business, such as an online purchase or a call to your business from a mobile phone.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  conversions as \"conversions\",\n  activity\nFROM google_cm_conversion_report\nWHERE\n  $__timeFilter(date) AND\n  brand in($Brand) AND \n  product in($Product) AND\n  campaign_name in($Campaign) AND \n  activity in ($Activity)\nGROUP BY time, activity\nORDER BY time"
    }
   ]
  },
  {
   "title": "Conversion Value",
   "type": "graph",
   "description": "Conversion Value is a measure of the value of all the conversions given a self defined value metric",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  conversions_value as \"conversions_value\",\n  activity\nFROM google_cm_conversion_report\nWHERE\n  $__timeFilter(date) AND\n  brand in($Brand) AND \n  product in($Product) AND \n  campaign_name in($Campaign) AND \n  activity in ($Activity)\nGROUP BY time, activity\nORDER BY time"
    }
   ]
  }
 ]
}